accelerate launch --num_processes 4 ../src/bert_tuning.py \
        --model_name answerdotai/ModernBERT-large \
        --data_path ../chain_slim_v1/ \
        --output_path ../res/ \
        --batch_size 16 \
        --epochs 5 \
        --seed 42 \
        --lr 5e-5 \
        --loss_fn pwr \
        --weight_decay 0.1 \
        --eval_strategy epoch \
        --gradient_checkpointing True